### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by fsuter** [TYPO3incubator/graphql#13]
Hi guys,
Opening an issue may not be the best way to get in touch, but I couldn't find any reference page for this initiative, nor a Slack channel or whatever else.
I would like to know that is the status of this initiative. I have a large customer project coming up where using this tool would be ideal. I installed it to create a proof of concept and it works beautifully, except for being very slow.
Are you still working on it or planning to? Could I contribute to it thanks to this customer of mine?
I would very much appreciate to be able to get in touch with someone and discuss the matter in more details.
TIA

**Comment by bmack** [comment]
Hey @fsuter,

GraphQL is currently not maintained (but possibly working). We waited to continue here because we wanted to build a "Read API" for the database abstraction, and went on to solve some conceptual issues with TYPO3 so this Read API could be easier to build:
* Workspaces: "pid=-1" (Resolved TYPO3 v10 LTS)
* Workspaces: Removal of Move Placeholders (Resolved in TYPO3 v11.0)
* Workspaces: Removal of New Placeholders (Resolved in TYPO3 v11.0)

The next steps would be to work on a more consistent language handling (sys_language_uid=-1 and sorting of records within languages), to then build the Read API, but seems like the Initiative itself did not continue working.

There is a Slack Channel (cig-persistence) on the TYPO3 Slack.

**Comment by ohader** [comment]
https://typo3.org/community/teams/typo3-development/initiatives lists the "Datahandler & Persistence Initiative" which is not active any more. The amount of people was limited all the time and in the end it basically was just Benni and me.

The read API Benni referred to is like a "context aware query API" - e.g. "give me content records with all nested image references, and please resolve language and workspace aspects". On a database & query level that requires lots of joins or sub-queries - that's basically the reason why complexity (`pid=-1`, workspace placeholders, `sys_language_uid=-1`) needs to be reduced first.

**Comment by fsuter** [comment]
Thanks for your answers. Continuing discussion on Slack.
